Repository beethub/environment-beet-dev, pull requests merged in 2020-02, with the labels that each got.

#1 chore(deps): bump https://github.com/beethub/TestApp.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/beethub-testapp-sr.yaml
Labels: size/M, updatebot

#2 Rename repository
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/beethub-testapp-sr.yaml
Labels: size/S

#3 chore(deps): bump https://github.com/beethub/receipt-api.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/beethub-receipt-api-sr.yaml
Labels: size/S, updatebot
